// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ClockResyncRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static ClockResyncRequest getRootAsClockResyncRequest(ByteBuffer _bb) { return getRootAsClockResyncRequest(_bb, new ClockResyncRequest()); }
  public static ClockResyncRequest getRootAsClockResyncRequest(ByteBuffer _bb, ClockResyncRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ClockResyncRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int sampleCount() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createClockResyncRequest(FlatBufferBuilder builder,
      int sampleCount) {
    builder.startTable(1);
    ClockResyncRequest.addSampleCount(builder, sampleCount);
    return ClockResyncRequest.endClockResyncRequest(builder);
  }

  public static void startClockResyncRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addSampleCount(FlatBufferBuilder builder, int sampleCount) { builder.addInt(0, sampleCount, 0); }
  public static int endClockResyncRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ClockResyncRequest get(int j) { return get(new ClockResyncRequest(), j); }
    public ClockResyncRequest get(ClockResyncRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

