// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DeviceTelemetry extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static DeviceTelemetry getRootAsDeviceTelemetry(ByteBuffer _bb) { return getRootAsDeviceTelemetry(_bb, new DeviceTelemetry()); }
  public static DeviceTelemetry getRootAsDeviceTelemetry(ByteBuffer _bb, DeviceTelemetry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DeviceTelemetry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String stableDeviceId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stableDeviceIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer stableDeviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte role() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int sensitivity() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int latencyMs() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public boolean clockSynced() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int analysisWidth() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public int analysisHeight() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public long timestampMillis() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createDeviceTelemetry(FlatBufferBuilder builder,
      int stableDeviceIdOffset,
      byte role,
      int sensitivity,
      int latencyMs,
      boolean clockSynced,
      int analysisWidth,
      int analysisHeight,
      long timestampMillis) {
    builder.startTable(8);
    DeviceTelemetry.addTimestampMillis(builder, timestampMillis);
    DeviceTelemetry.addAnalysisHeight(builder, analysisHeight);
    DeviceTelemetry.addAnalysisWidth(builder, analysisWidth);
    DeviceTelemetry.addLatencyMs(builder, latencyMs);
    DeviceTelemetry.addSensitivity(builder, sensitivity);
    DeviceTelemetry.addStableDeviceId(builder, stableDeviceIdOffset);
    DeviceTelemetry.addClockSynced(builder, clockSynced);
    DeviceTelemetry.addRole(builder, role);
    return DeviceTelemetry.endDeviceTelemetry(builder);
  }

  public static void startDeviceTelemetry(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addStableDeviceId(FlatBufferBuilder builder, int stableDeviceIdOffset) { builder.addOffset(0, stableDeviceIdOffset, 0); }
  public static void addRole(FlatBufferBuilder builder, byte role) { builder.addByte(1, role, 0); }
  public static void addSensitivity(FlatBufferBuilder builder, int sensitivity) { builder.addInt(2, sensitivity, 0); }
  public static void addLatencyMs(FlatBufferBuilder builder, int latencyMs) { builder.addInt(3, latencyMs, -1); }
  public static void addClockSynced(FlatBufferBuilder builder, boolean clockSynced) { builder.addBoolean(4, clockSynced, false); }
  public static void addAnalysisWidth(FlatBufferBuilder builder, int analysisWidth) { builder.addInt(5, analysisWidth, -1); }
  public static void addAnalysisHeight(FlatBufferBuilder builder, int analysisHeight) { builder.addInt(6, analysisHeight, -1); }
  public static void addTimestampMillis(FlatBufferBuilder builder, long timestampMillis) { builder.addLong(7, timestampMillis, 0L); }
  public static int endDeviceTelemetry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DeviceTelemetry get(int j) { return get(new DeviceTelemetry(), j); }
    public DeviceTelemetry get(DeviceTelemetry obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

