// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DeviceIdentity extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static DeviceIdentity getRootAsDeviceIdentity(ByteBuffer _bb) { return getRootAsDeviceIdentity(_bb, new DeviceIdentity()); }
  public static DeviceIdentity getRootAsDeviceIdentity(ByteBuffer _bb, DeviceIdentity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DeviceIdentity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String stableDeviceId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stableDeviceIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer stableDeviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String deviceName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deviceNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer deviceNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createDeviceIdentity(FlatBufferBuilder builder,
      int stableDeviceIdOffset,
      int deviceNameOffset) {
    builder.startTable(2);
    DeviceIdentity.addDeviceName(builder, deviceNameOffset);
    DeviceIdentity.addStableDeviceId(builder, stableDeviceIdOffset);
    return DeviceIdentity.endDeviceIdentity(builder);
  }

  public static void startDeviceIdentity(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStableDeviceId(FlatBufferBuilder builder, int stableDeviceIdOffset) { builder.addOffset(0, stableDeviceIdOffset, 0); }
  public static void addDeviceName(FlatBufferBuilder builder, int deviceNameOffset) { builder.addOffset(1, deviceNameOffset, 0); }
  public static int endDeviceIdentity(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DeviceIdentity get(int j) { return get(new DeviceIdentity(), j); }
    public DeviceIdentity get(DeviceIdentity obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

