// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HostControlCommand extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static HostControlCommand getRootAsHostControlCommand(ByteBuffer _bb) { return getRootAsHostControlCommand(_bb, new HostControlCommand()); }
  public static HostControlCommand getRootAsHostControlCommand(ByteBuffer _bb, HostControlCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HostControlCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String action() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer actionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer actionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int intValue() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean hasIntValue() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createHostControlCommand(FlatBufferBuilder builder,
      int actionOffset,
      int intValue,
      boolean hasIntValue) {
    builder.startTable(3);
    HostControlCommand.addIntValue(builder, intValue);
    HostControlCommand.addAction(builder, actionOffset);
    HostControlCommand.addHasIntValue(builder, hasIntValue);
    return HostControlCommand.endHostControlCommand(builder);
  }

  public static void startHostControlCommand(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addAction(FlatBufferBuilder builder, int actionOffset) { builder.addOffset(0, actionOffset, 0); }
  public static void addIntValue(FlatBufferBuilder builder, int intValue) { builder.addInt(1, intValue, 0); }
  public static void addHasIntValue(FlatBufferBuilder builder, boolean hasIntValue) { builder.addBoolean(2, hasIntValue, false); }
  public static int endHostControlCommand(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HostControlCommand get(int j) { return get(new HostControlCommand(), j); }
    public HostControlCommand get(HostControlCommand obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

