// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LapResult extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static LapResult getRootAsLapResult(ByteBuffer _bb) { return getRootAsLapResult(_bb, new LapResult()); }
  public static LapResult getRootAsLapResult(ByteBuffer _bb, LapResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LapResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String senderDeviceName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer senderDeviceNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer senderDeviceNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long startedSensorNanos() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long stoppedSensorNanos() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createLapResult(FlatBufferBuilder builder,
      int senderDeviceNameOffset,
      long startedSensorNanos,
      long stoppedSensorNanos) {
    builder.startTable(3);
    LapResult.addStoppedSensorNanos(builder, stoppedSensorNanos);
    LapResult.addStartedSensorNanos(builder, startedSensorNanos);
    LapResult.addSenderDeviceName(builder, senderDeviceNameOffset);
    return LapResult.endLapResult(builder);
  }

  public static void startLapResult(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSenderDeviceName(FlatBufferBuilder builder, int senderDeviceNameOffset) { builder.addOffset(0, senderDeviceNameOffset, 0); }
  public static void addStartedSensorNanos(FlatBufferBuilder builder, long startedSensorNanos) { builder.addLong(1, startedSensorNanos, 0L); }
  public static void addStoppedSensorNanos(FlatBufferBuilder builder, long stoppedSensorNanos) { builder.addLong(2, stoppedSensorNanos, 0L); }
  public static int endLapResult(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LapResult get(int j) { return get(new LapResult(), j); }
    public LapResult get(LapResult obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

