// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionSplitMark extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionSplitMark getRootAsSessionSplitMark(ByteBuffer _bb) { return getRootAsSessionSplitMark(_bb, new SessionSplitMark()); }
  public static SessionSplitMark getRootAsSessionSplitMark(ByteBuffer _bb, SessionSplitMark obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionSplitMark __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte role() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long hostSensorNanos() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSessionSplitMark(FlatBufferBuilder builder,
      byte role,
      long hostSensorNanos) {
    builder.startTable(2);
    SessionSplitMark.addHostSensorNanos(builder, hostSensorNanos);
    SessionSplitMark.addRole(builder, role);
    return SessionSplitMark.endSessionSplitMark(builder);
  }

  public static void startSessionSplitMark(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRole(FlatBufferBuilder builder, byte role) { builder.addByte(0, role, 0); }
  public static void addHostSensorNanos(FlatBufferBuilder builder, long hostSensorNanos) { builder.addLong(1, hostSensorNanos, 0L); }
  public static int endSessionSplitMark(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionSplitMark get(int j) { return get(new SessionSplitMark(), j); }
    public SessionSplitMark get(SessionSplitMark obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

