// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionSnapshotDevice extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionSnapshotDevice getRootAsSessionSnapshotDevice(ByteBuffer _bb) { return getRootAsSessionSnapshotDevice(_bb, new SessionSnapshotDevice()); }
  public static SessionSnapshotDevice getRootAsSessionSnapshotDevice(ByteBuffer _bb, SessionSnapshotDevice obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionSnapshotDevice __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String role() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roleAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer roleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String cameraFacing() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cameraFacingAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer cameraFacingInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public boolean isLocal() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createSessionSnapshotDevice(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset,
      int roleOffset,
      int cameraFacingOffset,
      boolean isLocal) {
    builder.startTable(5);
    SessionSnapshotDevice.addCameraFacing(builder, cameraFacingOffset);
    SessionSnapshotDevice.addRole(builder, roleOffset);
    SessionSnapshotDevice.addName(builder, nameOffset);
    SessionSnapshotDevice.addId(builder, idOffset);
    SessionSnapshotDevice.addIsLocal(builder, isLocal);
    return SessionSnapshotDevice.endSessionSnapshotDevice(builder);
  }

  public static void startSessionSnapshotDevice(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addRole(FlatBufferBuilder builder, int roleOffset) { builder.addOffset(2, roleOffset, 0); }
  public static void addCameraFacing(FlatBufferBuilder builder, int cameraFacingOffset) { builder.addOffset(3, cameraFacingOffset, 0); }
  public static void addIsLocal(FlatBufferBuilder builder, boolean isLocal) { builder.addBoolean(4, isLocal, false); }
  public static int endSessionSnapshotDevice(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionSnapshotDevice get(int j) { return get(new SessionSnapshotDevice(), j); }
    public SessionSnapshotDevice get(SessionSnapshotDevice obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

