// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionSnapshot extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionSnapshot getRootAsSessionSnapshot(ByteBuffer _bb) { return getRootAsSessionSnapshot(_bb, new SessionSnapshot()); }
  public static SessionSnapshot getRootAsSessionSnapshot(ByteBuffer _bb, SessionSnapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String stage() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer stageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean monitoringActive() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public SprintSync.Schema.SessionSnapshotDevice devices(int j) { return devices(new SprintSync.Schema.SessionSnapshotDevice(), j); }
  public SprintSync.Schema.SessionSnapshotDevice devices(SprintSync.Schema.SessionSnapshotDevice obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int devicesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public SprintSync.Schema.SessionSnapshotDevice.Vector devicesVector() { return devicesVector(new SprintSync.Schema.SessionSnapshotDevice.Vector()); }
  public SprintSync.Schema.SessionSnapshotDevice.Vector devicesVector(SprintSync.Schema.SessionSnapshotDevice.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long hostStartSensorNanos() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long hostStopSensorNanos() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public SprintSync.Schema.SessionSplitMark hostSplitMarks(int j) { return hostSplitMarks(new SprintSync.Schema.SessionSplitMark(), j); }
  public SprintSync.Schema.SessionSplitMark hostSplitMarks(SprintSync.Schema.SessionSplitMark obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int hostSplitMarksLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public SprintSync.Schema.SessionSplitMark.Vector hostSplitMarksVector() { return hostSplitMarksVector(new SprintSync.Schema.SessionSplitMark.Vector()); }
  public SprintSync.Schema.SessionSplitMark.Vector hostSplitMarksVector(SprintSync.Schema.SessionSplitMark.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String runId() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer runIdAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer runIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public long hostSensorMinusElapsedNanos() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long hostGpsUtcOffsetNanos() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long hostGpsFixAgeNanos() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public String selfDeviceId() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer selfDeviceIdAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer selfDeviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public String anchorDeviceId() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer anchorDeviceIdAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer anchorDeviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public String anchorState() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer anchorStateAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer anchorStateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }

  public static int createSessionSnapshot(FlatBufferBuilder builder,
      int stageOffset,
      boolean monitoringActive,
      int devicesOffset,
      long hostStartSensorNanos,
      long hostStopSensorNanos,
      int hostSplitMarksOffset,
      int runIdOffset,
      long hostSensorMinusElapsedNanos,
      long hostGpsUtcOffsetNanos,
      long hostGpsFixAgeNanos,
      int selfDeviceIdOffset,
      int anchorDeviceIdOffset,
      int anchorStateOffset) {
    builder.startTable(13);
    SessionSnapshot.addHostGpsFixAgeNanos(builder, hostGpsFixAgeNanos);
    SessionSnapshot.addHostGpsUtcOffsetNanos(builder, hostGpsUtcOffsetNanos);
    SessionSnapshot.addHostSensorMinusElapsedNanos(builder, hostSensorMinusElapsedNanos);
    SessionSnapshot.addHostStopSensorNanos(builder, hostStopSensorNanos);
    SessionSnapshot.addHostStartSensorNanos(builder, hostStartSensorNanos);
    SessionSnapshot.addAnchorState(builder, anchorStateOffset);
    SessionSnapshot.addAnchorDeviceId(builder, anchorDeviceIdOffset);
    SessionSnapshot.addSelfDeviceId(builder, selfDeviceIdOffset);
    SessionSnapshot.addRunId(builder, runIdOffset);
    SessionSnapshot.addHostSplitMarks(builder, hostSplitMarksOffset);
    SessionSnapshot.addDevices(builder, devicesOffset);
    SessionSnapshot.addStage(builder, stageOffset);
    SessionSnapshot.addMonitoringActive(builder, monitoringActive);
    return SessionSnapshot.endSessionSnapshot(builder);
  }

  public static void startSessionSnapshot(FlatBufferBuilder builder) { builder.startTable(13); }
  public static void addStage(FlatBufferBuilder builder, int stageOffset) { builder.addOffset(0, stageOffset, 0); }
  public static void addMonitoringActive(FlatBufferBuilder builder, boolean monitoringActive) { builder.addBoolean(1, monitoringActive, false); }
  public static void addDevices(FlatBufferBuilder builder, int devicesOffset) { builder.addOffset(2, devicesOffset, 0); }
  public static int createDevicesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDevicesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addHostStartSensorNanos(FlatBufferBuilder builder, long hostStartSensorNanos) { builder.addLong(3, hostStartSensorNanos, -1L); }
  public static void addHostStopSensorNanos(FlatBufferBuilder builder, long hostStopSensorNanos) { builder.addLong(4, hostStopSensorNanos, -1L); }
  public static void addHostSplitMarks(FlatBufferBuilder builder, int hostSplitMarksOffset) { builder.addOffset(5, hostSplitMarksOffset, 0); }
  public static int createHostSplitMarksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHostSplitMarksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRunId(FlatBufferBuilder builder, int runIdOffset) { builder.addOffset(6, runIdOffset, 0); }
  public static void addHostSensorMinusElapsedNanos(FlatBufferBuilder builder, long hostSensorMinusElapsedNanos) { builder.addLong(7, hostSensorMinusElapsedNanos, -1L); }
  public static void addHostGpsUtcOffsetNanos(FlatBufferBuilder builder, long hostGpsUtcOffsetNanos) { builder.addLong(8, hostGpsUtcOffsetNanos, -1L); }
  public static void addHostGpsFixAgeNanos(FlatBufferBuilder builder, long hostGpsFixAgeNanos) { builder.addLong(9, hostGpsFixAgeNanos, -1L); }
  public static void addSelfDeviceId(FlatBufferBuilder builder, int selfDeviceIdOffset) { builder.addOffset(10, selfDeviceIdOffset, 0); }
  public static void addAnchorDeviceId(FlatBufferBuilder builder, int anchorDeviceIdOffset) { builder.addOffset(11, anchorDeviceIdOffset, 0); }
  public static void addAnchorState(FlatBufferBuilder builder, int anchorStateOffset) { builder.addOffset(12, anchorStateOffset, 0); }
  public static int endSessionSnapshot(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionSnapshot get(int j) { return get(new SessionSnapshot(), j); }
    public SessionSnapshot get(SessionSnapshot obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

