// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionTrigger extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionTrigger getRootAsSessionTrigger(ByteBuffer _bb) { return getRootAsSessionTrigger(_bb, new SessionTrigger()); }
  public static SessionTrigger getRootAsSessionTrigger(ByteBuffer _bb, SessionTrigger obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionTrigger __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String triggerType() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer triggerTypeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer triggerTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int splitIndex() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public long triggerSensorNanos() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSessionTrigger(FlatBufferBuilder builder,
      int triggerTypeOffset,
      int splitIndex,
      long triggerSensorNanos) {
    builder.startTable(3);
    SessionTrigger.addTriggerSensorNanos(builder, triggerSensorNanos);
    SessionTrigger.addSplitIndex(builder, splitIndex);
    SessionTrigger.addTriggerType(builder, triggerTypeOffset);
    return SessionTrigger.endSessionTrigger(builder);
  }

  public static void startSessionTrigger(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addTriggerType(FlatBufferBuilder builder, int triggerTypeOffset) { builder.addOffset(0, triggerTypeOffset, 0); }
  public static void addSplitIndex(FlatBufferBuilder builder, int splitIndex) { builder.addInt(1, splitIndex, -1); }
  public static void addTriggerSensorNanos(FlatBufferBuilder builder, long triggerSensorNanos) { builder.addLong(2, triggerSensorNanos, 0L); }
  public static int endSessionTrigger(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // triggerType
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionTrigger get(int j) { return get(new SessionTrigger(), j); }
    public SessionTrigger get(SessionTrigger obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

