// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

@SuppressWarnings("unused")
public final class SessionDeviceRole {
  private SessionDeviceRole() { }
  public static final byte UNASSIGNED = 0;
  public static final byte START = 1;
  public static final byte SPLIT1 = 2;
  public static final byte SPLIT2 = 3;
  public static final byte SPLIT3 = 4;
  public static final byte SPLIT4 = 5;
  public static final byte STOP = 6;
  public static final byte DISPLAY = 7;

  public static final String[] names = { "UNASSIGNED", "START", "SPLIT1", "SPLIT2", "SPLIT3", "SPLIT4", "STOP", "DISPLAY", };

  public static String name(int e) { return names[e]; }
}

