// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionTimelineSnapshot extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionTimelineSnapshot getRootAsSessionTimelineSnapshot(ByteBuffer _bb) { return getRootAsSessionTimelineSnapshot(_bb, new SessionTimelineSnapshot()); }
  public static SessionTimelineSnapshot getRootAsSessionTimelineSnapshot(ByteBuffer _bb, SessionTimelineSnapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionTimelineSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long hostStartSensorNanos() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long hostStopSensorNanos() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public SprintSync.Schema.SessionSplitMark hostSplitMarks(int j) { return hostSplitMarks(new SprintSync.Schema.SessionSplitMark(), j); }
  public SprintSync.Schema.SessionSplitMark hostSplitMarks(SprintSync.Schema.SessionSplitMark obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int hostSplitMarksLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public SprintSync.Schema.SessionSplitMark.Vector hostSplitMarksVector() { return hostSplitMarksVector(new SprintSync.Schema.SessionSplitMark.Vector()); }
  public SprintSync.Schema.SessionSplitMark.Vector hostSplitMarksVector(SprintSync.Schema.SessionSplitMark.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long sentElapsedNanos() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSessionTimelineSnapshot(FlatBufferBuilder builder,
      long hostStartSensorNanos,
      long hostStopSensorNanos,
      int hostSplitMarksOffset,
      long sentElapsedNanos) {
    builder.startTable(4);
    SessionTimelineSnapshot.addSentElapsedNanos(builder, sentElapsedNanos);
    SessionTimelineSnapshot.addHostStopSensorNanos(builder, hostStopSensorNanos);
    SessionTimelineSnapshot.addHostStartSensorNanos(builder, hostStartSensorNanos);
    SessionTimelineSnapshot.addHostSplitMarks(builder, hostSplitMarksOffset);
    return SessionTimelineSnapshot.endSessionTimelineSnapshot(builder);
  }

  public static void startSessionTimelineSnapshot(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addHostStartSensorNanos(FlatBufferBuilder builder, long hostStartSensorNanos) { builder.addLong(0, hostStartSensorNanos, -1L); }
  public static void addHostStopSensorNanos(FlatBufferBuilder builder, long hostStopSensorNanos) { builder.addLong(1, hostStopSensorNanos, -1L); }
  public static void addHostSplitMarks(FlatBufferBuilder builder, int hostSplitMarksOffset) { builder.addOffset(2, hostSplitMarksOffset, 0); }
  public static int createHostSplitMarksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHostSplitMarksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSentElapsedNanos(FlatBufferBuilder builder, long sentElapsedNanos) { builder.addLong(3, sentElapsedNanos, 0L); }
  public static int endSessionTimelineSnapshot(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionTimelineSnapshot get(int j) { return get(new SessionTimelineSnapshot(), j); }
    public SessionTimelineSnapshot get(SessionTimelineSnapshot obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

