// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SessionTriggerRequest extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SessionTriggerRequest getRootAsSessionTriggerRequest(ByteBuffer _bb) { return getRootAsSessionTriggerRequest(_bb, new SessionTriggerRequest()); }
  public static SessionTriggerRequest getRootAsSessionTriggerRequest(ByteBuffer _bb, SessionTriggerRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionTriggerRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte role() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long triggerSensorNanos() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long mappedHostSensorNanos() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public String sourceDeviceId() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sourceDeviceIdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer sourceDeviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long sourceElapsedNanos() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long mappedAnchorElapsedNanos() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }

  public static int createSessionTriggerRequest(FlatBufferBuilder builder,
      byte role,
      long triggerSensorNanos,
      long mappedHostSensorNanos,
      int sourceDeviceIdOffset,
      long sourceElapsedNanos,
      long mappedAnchorElapsedNanos) {
    builder.startTable(6);
    SessionTriggerRequest.addMappedAnchorElapsedNanos(builder, mappedAnchorElapsedNanos);
    SessionTriggerRequest.addSourceElapsedNanos(builder, sourceElapsedNanos);
    SessionTriggerRequest.addMappedHostSensorNanos(builder, mappedHostSensorNanos);
    SessionTriggerRequest.addTriggerSensorNanos(builder, triggerSensorNanos);
    SessionTriggerRequest.addSourceDeviceId(builder, sourceDeviceIdOffset);
    SessionTriggerRequest.addRole(builder, role);
    return SessionTriggerRequest.endSessionTriggerRequest(builder);
  }

  public static void startSessionTriggerRequest(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addRole(FlatBufferBuilder builder, byte role) { builder.addByte(0, role, 0); }
  public static void addTriggerSensorNanos(FlatBufferBuilder builder, long triggerSensorNanos) { builder.addLong(1, triggerSensorNanos, 0L); }
  public static void addMappedHostSensorNanos(FlatBufferBuilder builder, long mappedHostSensorNanos) { builder.addLong(2, mappedHostSensorNanos, -1L); }
  public static void addSourceDeviceId(FlatBufferBuilder builder, int sourceDeviceIdOffset) { builder.addOffset(3, sourceDeviceIdOffset, 0); }
  public static void addSourceElapsedNanos(FlatBufferBuilder builder, long sourceElapsedNanos) { builder.addLong(4, sourceElapsedNanos, 0L); }
  public static void addMappedAnchorElapsedNanos(FlatBufferBuilder builder, long mappedAnchorElapsedNanos) { builder.addLong(5, mappedAnchorElapsedNanos, -1L); }
  public static int endSessionTriggerRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 10);  // sourceDeviceId
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionTriggerRequest get(int j) { return get(new SessionTriggerRequest(), j); }
    public SessionTriggerRequest get(SessionTriggerRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

