// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TelemetryEnvelope extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static TelemetryEnvelope getRootAsTelemetryEnvelope(ByteBuffer _bb) { return getRootAsTelemetryEnvelope(_bb, new TelemetryEnvelope()); }
  public static TelemetryEnvelope getRootAsTelemetryEnvelope(ByteBuffer _bb, TelemetryEnvelope obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TelemetryEnvelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte payloadType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.google.flatbuffers.Table payload(com.google.flatbuffers.Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createTelemetryEnvelope(FlatBufferBuilder builder,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(2);
    TelemetryEnvelope.addPayload(builder, payloadOffset);
    TelemetryEnvelope.addPayloadType(builder, payloadType);
    return TelemetryEnvelope.endTelemetryEnvelope(builder);
  }

  public static void startTelemetryEnvelope(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(0, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(1, payloadOffset, 0); }
  public static int endTelemetryEnvelope(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishTelemetryEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedTelemetryEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TelemetryEnvelope get(int j) { return get(new TelemetryEnvelope(), j); }
    public TelemetryEnvelope get(TelemetryEnvelope obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

