// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

@SuppressWarnings("unused")
public final class TelemetryPayload {
  private TelemetryPayload() { }
  public static final byte NONE = 0;
  public static final byte SessionTriggerRequest = 1;
  public static final byte SessionTrigger = 2;
  public static final byte SessionTimelineSnapshot = 3;
  public static final byte SessionSnapshot = 4;
  public static final byte TriggerRefinement = 5;
  public static final byte DeviceConfigUpdate = 6;
  public static final byte ClockResyncRequest = 7;
  public static final byte DeviceIdentity = 8;
  public static final byte DeviceTelemetry = 9;
  public static final byte LapResult = 10;

  public static final String[] names = { "NONE", "SessionTriggerRequest", "SessionTrigger", "SessionTimelineSnapshot", "SessionSnapshot", "TriggerRefinement", "DeviceConfigUpdate", "ClockResyncRequest", "DeviceIdentity", "DeviceTelemetry", "LapResult", };

  public static String name(int e) { return names[e]; }
}

