// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TriggerRefinement extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static TriggerRefinement getRootAsTriggerRefinement(ByteBuffer _bb) { return getRootAsTriggerRefinement(_bb, new TriggerRefinement()); }
  public static TriggerRefinement getRootAsTriggerRefinement(ByteBuffer _bb, TriggerRefinement obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TriggerRefinement __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String runId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer runIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer runIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte role() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long provisionalHostSensorNanos() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long refinedHostSensorNanos() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createTriggerRefinement(FlatBufferBuilder builder,
      int runIdOffset,
      byte role,
      long provisionalHostSensorNanos,
      long refinedHostSensorNanos) {
    builder.startTable(4);
    TriggerRefinement.addRefinedHostSensorNanos(builder, refinedHostSensorNanos);
    TriggerRefinement.addProvisionalHostSensorNanos(builder, provisionalHostSensorNanos);
    TriggerRefinement.addRunId(builder, runIdOffset);
    TriggerRefinement.addRole(builder, role);
    return TriggerRefinement.endTriggerRefinement(builder);
  }

  public static void startTriggerRefinement(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addRunId(FlatBufferBuilder builder, int runIdOffset) { builder.addOffset(0, runIdOffset, 0); }
  public static void addRole(FlatBufferBuilder builder, byte role) { builder.addByte(1, role, 0); }
  public static void addProvisionalHostSensorNanos(FlatBufferBuilder builder, long provisionalHostSensorNanos) { builder.addLong(2, provisionalHostSensorNanos, 0L); }
  public static void addRefinedHostSensorNanos(FlatBufferBuilder builder, long refinedHostSensorNanos) { builder.addLong(3, refinedHostSensorNanos, 0L); }
  public static int endTriggerRefinement(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TriggerRefinement get(int j) { return get(new TriggerRefinement(), j); }
    public TriggerRefinement get(TriggerRefinement obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

