// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ClockResyncRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ClockResyncRequest {
        __init(_i, _bb)
        return this
    }
    val sampleCount : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsClockResyncRequest(_bb: ByteBuffer): ClockResyncRequest = getRootAsClockResyncRequest(_bb, ClockResyncRequest())
        fun getRootAsClockResyncRequest(_bb: ByteBuffer, obj: ClockResyncRequest): ClockResyncRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createClockResyncRequest(builder: FlatBufferBuilder, sampleCount: Int) : Int {
            builder.startTable(1)
            addSampleCount(builder, sampleCount)
            return endClockResyncRequest(builder)
        }
        fun startClockResyncRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addSampleCount(builder: FlatBufferBuilder, sampleCount: Int) = builder.addInt(0, sampleCount, 0)
        fun endClockResyncRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
