// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceIdentity : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceIdentity {
        __init(_i, _bb)
        return this
    }
    val stableDeviceId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stableDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun stableDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val deviceName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val deviceNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun deviceNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceIdentity(_bb: ByteBuffer): DeviceIdentity = getRootAsDeviceIdentity(_bb, DeviceIdentity())
        fun getRootAsDeviceIdentity(_bb: ByteBuffer, obj: DeviceIdentity): DeviceIdentity {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceIdentity(builder: FlatBufferBuilder, stableDeviceIdOffset: Int, deviceNameOffset: Int) : Int {
            builder.startTable(2)
            addDeviceName(builder, deviceNameOffset)
            addStableDeviceId(builder, stableDeviceIdOffset)
            return endDeviceIdentity(builder)
        }
        fun startDeviceIdentity(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addStableDeviceId(builder: FlatBufferBuilder, stableDeviceId: Int) = builder.addOffset(0, stableDeviceId, 0)
        fun addDeviceName(builder: FlatBufferBuilder, deviceName: Int) = builder.addOffset(1, deviceName, 0)
        fun endDeviceIdentity(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
