// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceTelemetry : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceTelemetry {
        __init(_i, _bb)
        return this
    }
    val stableDeviceId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stableDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun stableDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val role : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val sensitivity : Int
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val latencyMs : Int
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    val clockSynced : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val analysisWidth : Int
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    val analysisHeight : Int
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    val timestampMillis : Long
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceTelemetry(_bb: ByteBuffer): DeviceTelemetry = getRootAsDeviceTelemetry(_bb, DeviceTelemetry())
        fun getRootAsDeviceTelemetry(_bb: ByteBuffer, obj: DeviceTelemetry): DeviceTelemetry {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceTelemetry(builder: FlatBufferBuilder, stableDeviceIdOffset: Int, role: Byte, sensitivity: Int, latencyMs: Int, clockSynced: Boolean, analysisWidth: Int, analysisHeight: Int, timestampMillis: Long) : Int {
            builder.startTable(8)
            addTimestampMillis(builder, timestampMillis)
            addAnalysisHeight(builder, analysisHeight)
            addAnalysisWidth(builder, analysisWidth)
            addLatencyMs(builder, latencyMs)
            addSensitivity(builder, sensitivity)
            addStableDeviceId(builder, stableDeviceIdOffset)
            addClockSynced(builder, clockSynced)
            addRole(builder, role)
            return endDeviceTelemetry(builder)
        }
        fun startDeviceTelemetry(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addStableDeviceId(builder: FlatBufferBuilder, stableDeviceId: Int) = builder.addOffset(0, stableDeviceId, 0)
        fun addRole(builder: FlatBufferBuilder, role: Byte) = builder.addByte(1, role, 0)
        fun addSensitivity(builder: FlatBufferBuilder, sensitivity: Int) = builder.addInt(2, sensitivity, 0)
        fun addLatencyMs(builder: FlatBufferBuilder, latencyMs: Int) = builder.addInt(3, latencyMs, -1)
        fun addClockSynced(builder: FlatBufferBuilder, clockSynced: Boolean) = builder.addBoolean(4, clockSynced, false)
        fun addAnalysisWidth(builder: FlatBufferBuilder, analysisWidth: Int) = builder.addInt(5, analysisWidth, -1)
        fun addAnalysisHeight(builder: FlatBufferBuilder, analysisHeight: Int) = builder.addInt(6, analysisHeight, -1)
        fun addTimestampMillis(builder: FlatBufferBuilder, timestampMillis: Long) = builder.addLong(7, timestampMillis, 0L)
        fun endDeviceTelemetry(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
