// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceConfigUpdate : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceConfigUpdate {
        __init(_i, _bb)
        return this
    }
    val targetStableDeviceId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val targetStableDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun targetStableDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val sensitivity : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceConfigUpdate(_bb: ByteBuffer): DeviceConfigUpdate = getRootAsDeviceConfigUpdate(_bb, DeviceConfigUpdate())
        fun getRootAsDeviceConfigUpdate(_bb: ByteBuffer, obj: DeviceConfigUpdate): DeviceConfigUpdate {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceConfigUpdate(builder: FlatBufferBuilder, targetStableDeviceIdOffset: Int, sensitivity: Int) : Int {
            builder.startTable(2)
            addSensitivity(builder, sensitivity)
            addTargetStableDeviceId(builder, targetStableDeviceIdOffset)
            return endDeviceConfigUpdate(builder)
        }
        fun startDeviceConfigUpdate(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addTargetStableDeviceId(builder: FlatBufferBuilder, targetStableDeviceId: Int) = builder.addOffset(0, targetStableDeviceId, 0)
        fun addSensitivity(builder: FlatBufferBuilder, sensitivity: Int) = builder.addInt(1, sensitivity, 0)
        fun endDeviceConfigUpdate(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
