// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class LapResult : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LapResult {
        __init(_i, _bb)
        return this
    }
    val senderDeviceName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val senderDeviceNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun senderDeviceNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val startedSensorNanos : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val stoppedSensorNanos : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLapResult(_bb: ByteBuffer): LapResult = getRootAsLapResult(_bb, LapResult())
        fun getRootAsLapResult(_bb: ByteBuffer, obj: LapResult): LapResult {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLapResult(builder: FlatBufferBuilder, senderDeviceNameOffset: Int, startedSensorNanos: Long, stoppedSensorNanos: Long) : Int {
            builder.startTable(3)
            addStoppedSensorNanos(builder, stoppedSensorNanos)
            addStartedSensorNanos(builder, startedSensorNanos)
            addSenderDeviceName(builder, senderDeviceNameOffset)
            return endLapResult(builder)
        }
        fun startLapResult(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addSenderDeviceName(builder: FlatBufferBuilder, senderDeviceName: Int) = builder.addOffset(0, senderDeviceName, 0)
        fun addStartedSensorNanos(builder: FlatBufferBuilder, startedSensorNanos: Long) = builder.addLong(1, startedSensorNanos, 0L)
        fun addStoppedSensorNanos(builder: FlatBufferBuilder, stoppedSensorNanos: Long) = builder.addLong(2, stoppedSensorNanos, 0L)
        fun endLapResult(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
