// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

@Suppress("unused")
class SessionDeviceRole private constructor() {
    companion object {
        const val UNASSIGNED: Byte = 0
        const val START: Byte = 1
        const val SPLIT1: Byte = 2
        const val SPLIT2: Byte = 3
        const val SPLIT3: Byte = 4
        const val SPLIT4: Byte = 5
        const val STOP: Byte = 6
        const val DISPLAY: Byte = 7
    }
}
