// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionTriggerRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionTriggerRequest {
        __init(_i, _bb)
        return this
    }
    val role : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val triggerSensorNanos : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val mappedHostSensorNanos : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val sourceDeviceId : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field sourceDeviceId")
            }
        }
    val sourceDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun sourceDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val sourceElapsedNanos : Long
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val mappedAnchorElapsedNanos : Long
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionTriggerRequest(_bb: ByteBuffer): SessionTriggerRequest = getRootAsSessionTriggerRequest(_bb, SessionTriggerRequest())
        fun getRootAsSessionTriggerRequest(_bb: ByteBuffer, obj: SessionTriggerRequest): SessionTriggerRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionTriggerRequest(builder: FlatBufferBuilder, role: Byte, triggerSensorNanos: Long, mappedHostSensorNanos: Long, sourceDeviceIdOffset: Int, sourceElapsedNanos: Long, mappedAnchorElapsedNanos: Long) : Int {
            builder.startTable(6)
            addMappedAnchorElapsedNanos(builder, mappedAnchorElapsedNanos)
            addSourceElapsedNanos(builder, sourceElapsedNanos)
            addMappedHostSensorNanos(builder, mappedHostSensorNanos)
            addTriggerSensorNanos(builder, triggerSensorNanos)
            addSourceDeviceId(builder, sourceDeviceIdOffset)
            addRole(builder, role)
            return endSessionTriggerRequest(builder)
        }
        fun startSessionTriggerRequest(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addRole(builder: FlatBufferBuilder, role: Byte) = builder.addByte(0, role, 0)
        fun addTriggerSensorNanos(builder: FlatBufferBuilder, triggerSensorNanos: Long) = builder.addLong(1, triggerSensorNanos, 0L)
        fun addMappedHostSensorNanos(builder: FlatBufferBuilder, mappedHostSensorNanos: Long) = builder.addLong(2, mappedHostSensorNanos, -1L)
        fun addSourceDeviceId(builder: FlatBufferBuilder, sourceDeviceId: Int) = builder.addOffset(3, sourceDeviceId, 0)
        fun addSourceElapsedNanos(builder: FlatBufferBuilder, sourceElapsedNanos: Long) = builder.addLong(4, sourceElapsedNanos, 0L)
        fun addMappedAnchorElapsedNanos(builder: FlatBufferBuilder, mappedAnchorElapsedNanos: Long) = builder.addLong(5, mappedAnchorElapsedNanos, -1L)
        fun endSessionTriggerRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 10)
            return o
        }
    }
}
