// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionTimelineSnapshot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionTimelineSnapshot {
        __init(_i, _bb)
        return this
    }
    val hostStartSensorNanos : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val hostStopSensorNanos : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    fun hostSplitMarks(j: Int) : SprintSync.Schema.SessionSplitMark? = hostSplitMarks(SprintSync.Schema.SessionSplitMark(), j)
    fun hostSplitMarks(obj: SprintSync.Schema.SessionSplitMark, j: Int) : SprintSync.Schema.SessionSplitMark? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val hostSplitMarksLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val sentElapsedNanos : Long
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionTimelineSnapshot(_bb: ByteBuffer): SessionTimelineSnapshot = getRootAsSessionTimelineSnapshot(_bb, SessionTimelineSnapshot())
        fun getRootAsSessionTimelineSnapshot(_bb: ByteBuffer, obj: SessionTimelineSnapshot): SessionTimelineSnapshot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionTimelineSnapshot(builder: FlatBufferBuilder, hostStartSensorNanos: Long, hostStopSensorNanos: Long, hostSplitMarksOffset: Int, sentElapsedNanos: Long) : Int {
            builder.startTable(4)
            addSentElapsedNanos(builder, sentElapsedNanos)
            addHostStopSensorNanos(builder, hostStopSensorNanos)
            addHostStartSensorNanos(builder, hostStartSensorNanos)
            addHostSplitMarks(builder, hostSplitMarksOffset)
            return endSessionTimelineSnapshot(builder)
        }
        fun startSessionTimelineSnapshot(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addHostStartSensorNanos(builder: FlatBufferBuilder, hostStartSensorNanos: Long) = builder.addLong(0, hostStartSensorNanos, -1L)
        fun addHostStopSensorNanos(builder: FlatBufferBuilder, hostStopSensorNanos: Long) = builder.addLong(1, hostStopSensorNanos, -1L)
        fun addHostSplitMarks(builder: FlatBufferBuilder, hostSplitMarks: Int) = builder.addOffset(2, hostSplitMarks, 0)
        fun createHostSplitMarksVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startHostSplitMarksVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSentElapsedNanos(builder: FlatBufferBuilder, sentElapsedNanos: Long) = builder.addLong(3, sentElapsedNanos, 0L)
        fun endSessionTimelineSnapshot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
