// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionTrigger : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionTrigger {
        __init(_i, _bb)
        return this
    }
    val triggerType : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field triggerType")
            }
        }
    val triggerTypeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun triggerTypeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val splitIndex : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    val triggerSensorNanos : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionTrigger(_bb: ByteBuffer): SessionTrigger = getRootAsSessionTrigger(_bb, SessionTrigger())
        fun getRootAsSessionTrigger(_bb: ByteBuffer, obj: SessionTrigger): SessionTrigger {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionTrigger(builder: FlatBufferBuilder, triggerTypeOffset: Int, splitIndex: Int, triggerSensorNanos: Long) : Int {
            builder.startTable(3)
            addTriggerSensorNanos(builder, triggerSensorNanos)
            addSplitIndex(builder, splitIndex)
            addTriggerType(builder, triggerTypeOffset)
            return endSessionTrigger(builder)
        }
        fun startSessionTrigger(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addTriggerType(builder: FlatBufferBuilder, triggerType: Int) = builder.addOffset(0, triggerType, 0)
        fun addSplitIndex(builder: FlatBufferBuilder, splitIndex: Int) = builder.addInt(1, splitIndex, -1)
        fun addTriggerSensorNanos(builder: FlatBufferBuilder, triggerSensorNanos: Long) = builder.addLong(2, triggerSensorNanos, 0L)
        fun endSessionTrigger(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
