// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionSnapshot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionSnapshot {
        __init(_i, _bb)
        return this
    }
    val stage : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stageAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun stageInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val monitoringActive : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun devices(j: Int) : SprintSync.Schema.SessionSnapshotDevice? = devices(SprintSync.Schema.SessionSnapshotDevice(), j)
    fun devices(obj: SprintSync.Schema.SessionSnapshotDevice, j: Int) : SprintSync.Schema.SessionSnapshotDevice? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val devicesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val hostStartSensorNanos : Long
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val hostStopSensorNanos : Long
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    fun hostSplitMarks(j: Int) : SprintSync.Schema.SessionSplitMark? = hostSplitMarks(SprintSync.Schema.SessionSplitMark(), j)
    fun hostSplitMarks(obj: SprintSync.Schema.SessionSplitMark, j: Int) : SprintSync.Schema.SessionSplitMark? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val hostSplitMarksLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    val runId : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val runIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun runIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val hostSensorMinusElapsedNanos : Long
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val hostGpsUtcOffsetNanos : Long
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val hostGpsFixAgeNanos : Long
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val selfDeviceId : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val selfDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun selfDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    val anchorDeviceId : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val anchorDeviceIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(26, 1)
    fun anchorDeviceIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 26, 1)
    val anchorState : String?
        get() {
            val o = __offset(28)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val anchorStateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(28, 1)
    fun anchorStateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 28, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionSnapshot(_bb: ByteBuffer): SessionSnapshot = getRootAsSessionSnapshot(_bb, SessionSnapshot())
        fun getRootAsSessionSnapshot(_bb: ByteBuffer, obj: SessionSnapshot): SessionSnapshot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionSnapshot(builder: FlatBufferBuilder, stageOffset: Int, monitoringActive: Boolean, devicesOffset: Int, hostStartSensorNanos: Long, hostStopSensorNanos: Long, hostSplitMarksOffset: Int, runIdOffset: Int, hostSensorMinusElapsedNanos: Long, hostGpsUtcOffsetNanos: Long, hostGpsFixAgeNanos: Long, selfDeviceIdOffset: Int, anchorDeviceIdOffset: Int, anchorStateOffset: Int) : Int {
            builder.startTable(13)
            addHostGpsFixAgeNanos(builder, hostGpsFixAgeNanos)
            addHostGpsUtcOffsetNanos(builder, hostGpsUtcOffsetNanos)
            addHostSensorMinusElapsedNanos(builder, hostSensorMinusElapsedNanos)
            addHostStopSensorNanos(builder, hostStopSensorNanos)
            addHostStartSensorNanos(builder, hostStartSensorNanos)
            addAnchorState(builder, anchorStateOffset)
            addAnchorDeviceId(builder, anchorDeviceIdOffset)
            addSelfDeviceId(builder, selfDeviceIdOffset)
            addRunId(builder, runIdOffset)
            addHostSplitMarks(builder, hostSplitMarksOffset)
            addDevices(builder, devicesOffset)
            addStage(builder, stageOffset)
            addMonitoringActive(builder, monitoringActive)
            return endSessionSnapshot(builder)
        }
        fun startSessionSnapshot(builder: FlatBufferBuilder) = builder.startTable(13)
        fun addStage(builder: FlatBufferBuilder, stage: Int) = builder.addOffset(0, stage, 0)
        fun addMonitoringActive(builder: FlatBufferBuilder, monitoringActive: Boolean) = builder.addBoolean(1, monitoringActive, false)
        fun addDevices(builder: FlatBufferBuilder, devices: Int) = builder.addOffset(2, devices, 0)
        fun createDevicesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDevicesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addHostStartSensorNanos(builder: FlatBufferBuilder, hostStartSensorNanos: Long) = builder.addLong(3, hostStartSensorNanos, -1L)
        fun addHostStopSensorNanos(builder: FlatBufferBuilder, hostStopSensorNanos: Long) = builder.addLong(4, hostStopSensorNanos, -1L)
        fun addHostSplitMarks(builder: FlatBufferBuilder, hostSplitMarks: Int) = builder.addOffset(5, hostSplitMarks, 0)
        fun createHostSplitMarksVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startHostSplitMarksVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addRunId(builder: FlatBufferBuilder, runId: Int) = builder.addOffset(6, runId, 0)
        fun addHostSensorMinusElapsedNanos(builder: FlatBufferBuilder, hostSensorMinusElapsedNanos: Long) = builder.addLong(7, hostSensorMinusElapsedNanos, -1L)
        fun addHostGpsUtcOffsetNanos(builder: FlatBufferBuilder, hostGpsUtcOffsetNanos: Long) = builder.addLong(8, hostGpsUtcOffsetNanos, -1L)
        fun addHostGpsFixAgeNanos(builder: FlatBufferBuilder, hostGpsFixAgeNanos: Long) = builder.addLong(9, hostGpsFixAgeNanos, -1L)
        fun addSelfDeviceId(builder: FlatBufferBuilder, selfDeviceId: Int) = builder.addOffset(10, selfDeviceId, 0)
        fun addAnchorDeviceId(builder: FlatBufferBuilder, anchorDeviceId: Int) = builder.addOffset(11, anchorDeviceId, 0)
        fun addAnchorState(builder: FlatBufferBuilder, anchorState: Int) = builder.addOffset(12, anchorState, 0)
        fun endSessionSnapshot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
