// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionSnapshotDevice : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionSnapshotDevice {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val name : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val role : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val roleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun roleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val cameraFacing : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val cameraFacingAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun cameraFacingInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val isLocal : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionSnapshotDevice(_bb: ByteBuffer): SessionSnapshotDevice = getRootAsSessionSnapshotDevice(_bb, SessionSnapshotDevice())
        fun getRootAsSessionSnapshotDevice(_bb: ByteBuffer, obj: SessionSnapshotDevice): SessionSnapshotDevice {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionSnapshotDevice(builder: FlatBufferBuilder, idOffset: Int, nameOffset: Int, roleOffset: Int, cameraFacingOffset: Int, isLocal: Boolean) : Int {
            builder.startTable(5)
            addCameraFacing(builder, cameraFacingOffset)
            addRole(builder, roleOffset)
            addName(builder, nameOffset)
            addId(builder, idOffset)
            addIsLocal(builder, isLocal)
            return endSessionSnapshotDevice(builder)
        }
        fun startSessionSnapshotDevice(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(1, name, 0)
        fun addRole(builder: FlatBufferBuilder, role: Int) = builder.addOffset(2, role, 0)
        fun addCameraFacing(builder: FlatBufferBuilder, cameraFacing: Int) = builder.addOffset(3, cameraFacing, 0)
        fun addIsLocal(builder: FlatBufferBuilder, isLocal: Boolean) = builder.addBoolean(4, isLocal, false)
        fun endSessionSnapshotDevice(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
