// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SessionSplitMark : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SessionSplitMark {
        __init(_i, _bb)
        return this
    }
    val role : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val hostSensorNanos : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSessionSplitMark(_bb: ByteBuffer): SessionSplitMark = getRootAsSessionSplitMark(_bb, SessionSplitMark())
        fun getRootAsSessionSplitMark(_bb: ByteBuffer, obj: SessionSplitMark): SessionSplitMark {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSessionSplitMark(builder: FlatBufferBuilder, role: Byte, hostSensorNanos: Long) : Int {
            builder.startTable(2)
            addHostSensorNanos(builder, hostSensorNanos)
            addRole(builder, role)
            return endSessionSplitMark(builder)
        }
        fun startSessionSplitMark(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addRole(builder: FlatBufferBuilder, role: Byte) = builder.addByte(0, role, 0)
        fun addHostSensorNanos(builder: FlatBufferBuilder, hostSensorNanos: Long) = builder.addLong(1, hostSensorNanos, 0L)
        fun endSessionSplitMark(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
