// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TelemetryEnvelope : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TelemetryEnvelope {
        __init(_i, _bb)
        return this
    }
    val payloadType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun payload(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTelemetryEnvelope(_bb: ByteBuffer): TelemetryEnvelope = getRootAsTelemetryEnvelope(_bb, TelemetryEnvelope())
        fun getRootAsTelemetryEnvelope(_bb: ByteBuffer, obj: TelemetryEnvelope): TelemetryEnvelope {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTelemetryEnvelope(builder: FlatBufferBuilder, payloadType: UByte, payloadOffset: Int) : Int {
            builder.startTable(2)
            addPayload(builder, payloadOffset)
            addPayloadType(builder, payloadType)
            return endTelemetryEnvelope(builder)
        }
        fun startTelemetryEnvelope(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addPayloadType(builder: FlatBufferBuilder, payloadType: UByte) = builder.addByte(0, payloadType.toByte(), 0)
        fun addPayload(builder: FlatBufferBuilder, payload: Int) = builder.addOffset(1, payload, 0)
        fun endTelemetryEnvelope(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishTelemetryEnvelopeBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedTelemetryEnvelopeBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
