// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TriggerRefinement : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TriggerRefinement {
        __init(_i, _bb)
        return this
    }
    val runId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val runIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun runIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val role : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val provisionalHostSensorNanos : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val refinedHostSensorNanos : Long
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTriggerRefinement(_bb: ByteBuffer): TriggerRefinement = getRootAsTriggerRefinement(_bb, TriggerRefinement())
        fun getRootAsTriggerRefinement(_bb: ByteBuffer, obj: TriggerRefinement): TriggerRefinement {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTriggerRefinement(builder: FlatBufferBuilder, runIdOffset: Int, role: Byte, provisionalHostSensorNanos: Long, refinedHostSensorNanos: Long) : Int {
            builder.startTable(4)
            addRefinedHostSensorNanos(builder, refinedHostSensorNanos)
            addProvisionalHostSensorNanos(builder, provisionalHostSensorNanos)
            addRunId(builder, runIdOffset)
            addRole(builder, role)
            return endTriggerRefinement(builder)
        }
        fun startTriggerRefinement(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addRunId(builder: FlatBufferBuilder, runId: Int) = builder.addOffset(0, runId, 0)
        fun addRole(builder: FlatBufferBuilder, role: Byte) = builder.addByte(1, role, 0)
        fun addProvisionalHostSensorNanos(builder: FlatBufferBuilder, provisionalHostSensorNanos: Long) = builder.addLong(2, provisionalHostSensorNanos, 0L)
        fun addRefinedHostSensorNanos(builder: FlatBufferBuilder, refinedHostSensorNanos: Long) = builder.addLong(3, refinedHostSensorNanos, 0L)
        fun endTriggerRefinement(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
