build:
  maxIssues: 0

config:
  validation: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    ignoreDefaultParameters: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false
